(()=>{
const DG='wss://api.deepgram.com/v1/listen';
const BACKENDS=['http://127.0.0.1:3001','http://localhost:3001'];
const REPLY_TIMEOUT=120000,COMMAND_TIMEOUT=9000,FOLLOWUP_TIMEOUT=5200,WAKE_RESTART=1200,VOICE_OWNER_HEARTBEAT=1200,VOICE_OWNER_RETRY=1800,WAKE_READY_TIMEOUT=3000,WAKE_START_ACK_TIMEOUT=2500,ALERT_SYNC_INTERVAL=2000,ALERT_REPEAT_DELAY=2400;
const OVERLAY_PUSH_INTERVAL=160,OVERLAY_PUSH_DEBOUNCE=140,DOM_MUTATION_DEBOUNCE=160,DOM_MAINTENANCE_INTERVAL=2600,WAKE_TRANSIENT_ERRORS=new Map([['no-speech',220],['network',1200]]);
const WAKE=/\b(?:hades|ha\s+des|hedes|ades)\b/i;
const WAKE_PREFIX=/^\s*(?:hades|ha\s+des|hedes|ades)[\s,.:;!?-]*/i;
const S={settings:{bridgeEnabled:true,autoRun:true,voiceEnabled:true},backendOk:false,backendError:null,spotify:null,prompt:'',promptVersion:'',processed:new WeakSet(),seen:new Map(),exec:false,programmatic:false,voice:{cfg:false,key:'',wakeWord:'HADES',locale:'tr-TR',mode:'idle',err:'',stream:null,ctx:null,worklet:null,src:null,an:null,frame:0,wake:null,wakeStopping:false,recognizer:null,cmd:null,cmdOptions:null,wEpoch:0,cEpoch:0,restart:0,timeout:0,wakeAck:0,segments:[],interim:'',reply:null,speaking:false,lastSig:'',prefVoice:null,ttsEpoch:0,finalizing:false,lastSubmitSig:'',lastSubmitAt:0,overlaySig:'',overlayAt:0,overlayTimer:0,meterValue:0,instanceId:(crypto?.randomUUID?crypto.randomUUID():`hades-${Date.now()}-${Math.random().toString(16).slice(2)}`),owner:false,ownerBeat:0,ownerRetry:0},alert:{active:null,lastPollAt:0,lastSig:'',repeatTimer:0,loopEpoch:0,syncing:false},logs:[]};
let root,panel,hud,chips,logEl,toastHost,voiceLine,hudState,hudDetail,meter,hudMeter,voiceBtn,cbBridge,cbAuto,obs,timer,domTimer=0,domQueued=false,wakeBridgeBound=false,manualScheduleBound=false;
const LOGO_URL=chrome.runtime.getURL('hades-cover.png');
function ensureBrandAssets(){const apply=(rel)=>{let link=document.head.querySelector(`link[rel="${rel}"]`);if(!link){link=document.createElement('link');link.rel=rel;document.head.appendChild(link);}if(link.href!==LOGO_URL)link.href=LOGO_URL;};apply('icon');apply('shortcut icon');apply('apple-touch-icon');}
const log=(m)=>{S.logs.unshift(`[${new Date().toLocaleTimeString('tr-TR')}] ${m}`);S.logs=S.logs.slice(0,14);if(logEl){logEl.innerHTML='';S.logs.forEach(t=>{const p=document.createElement('p');p.textContent=t;logEl.appendChild(p);});}};
const chip=(t,tone)=>{const e=document.createElement('span');e.className='hades-bridge-chip';e.dataset.tone=tone;e.textContent=t;return e;};
const voiceMeta=()=>{if(S.alert.active)return{chip:S.alert.active.kind==='reminder'?'Hatırlatıcı çalıyor':'Alarm çalıyor',tone:'warn',detail:S.alert.active.detail||'Yerel zamanlayıcı aktif.'};if(!S.settings.voiceEnabled)return{chip:'Ses kapalı',tone:'warn',detail:'Ses akışı kapalı.'};if(S.voice.err)return{chip:'Ses hatası',tone:'warn',detail:S.voice.err};if(!S.voice.cfg)return{chip:'Ses hazırlanıyor',tone:'warn',detail:'Ses altyapısı hazırlanıyor.'};if(S.voice.mode==='starting')return{chip:'Ses başlıyor',tone:'warn',detail:`"${S.voice.wakeWord}" için mikrofon açılıyor.`};if(S.voice.mode==='wake')return{chip:'Wake dinliyor',tone:'ok',detail:`"${S.voice.wakeWord}" deyince seni dinleyecek.`};if(S.voice.mode==='command')return{chip:'Komut dinliyor',tone:'ok',detail:'Deepgram komutunu dinliyor, bitince mesajı gönderecek.'};if(S.voice.mode==='followup')return{chip:'Seni dinliyor',tone:'ok',detail:'Yanıttan sonra birkaç saniye daha seni bekliyor.'};if(S.voice.mode==='reply')return{chip:'Yanıt bekliyor',tone:'ok',detail:'HADES yanıtını bekliyor.'};if(S.voice.mode==='speaking')return{chip:'Yanıtı okuyor',tone:'ok',detail:S.voice.recognizer?'Chromium sesi aktif. Yeniden "HADES" diyerek kesebilirsin.':'Chromium sesi aktif.'};return{chip:'Ses hazır',tone:'ok',detail:`"${S.voice.wakeWord}" deyince dinlemeye başlayacak.`};};
const overlayState=()=>{const vm=voiceMeta();return{chip:vm.chip,tone:vm.tone,detail:vm.detail,mode:S.voice.mode||'idle',meter:Math.max(0,Math.min(100,Math.round(Number(S.voice.meterValue)||0)))};};
async function postOverlay(force=false){const payload=overlayState(),sig=JSON.stringify(payload),now=Date.now();if(!force&&sig===S.voice.overlaySig)return;if(!force&&now-S.voice.overlayAt<OVERLAY_PUSH_INTERVAL){if(S.voice.overlayTimer)return;S.voice.overlayTimer=setTimeout(()=>{S.voice.overlayTimer=0;void postOverlay(true);},OVERLAY_PUSH_DEBOUNCE);return;}S.voice.overlaySig=sig;S.voice.overlayAt=now;for(const base of BACKENDS){try{await fetch(`${base}/bridge/voice-overlay-state`,{method:'POST',headers:{'Content-Type':'application/json'},body:sig});break;}catch(_){}}}
const setMeters=(width='0%')=>{const raw=String(width||'').replace('%','').trim();S.voice.meterValue=Math.max(0,Math.min(100,Number(raw)||0));if(meter)meter.style.width=width;if(hudMeter)hudMeter.style.width=width;void postOverlay(false);};
const render=()=>{if(!chips)return;const spotifyAuthenticated=Boolean(S.spotify?.authenticated??S.spotify?.ready),spotifyDeviceReady=Boolean(S.spotify?.deviceReady),spotifyChip=spotifyDeviceReady?'Spotify hazır':(spotifyAuthenticated?'Spotify cihaz bekliyor':'Spotify girişi bekliyor');chips.innerHTML='';chips.appendChild(chip(S.backendOk?'Backend hazır':'Backend kapalı',S.backendOk?'ok':'warn'));chips.appendChild(chip(S.settings.bridgeEnabled?'AI köprüsü açık':'AI köprüsü kapalı',S.settings.bridgeEnabled?'ok':'warn'));chips.appendChild(chip(spotifyChip,spotifyDeviceReady?'ok':'warn'));const vm=voiceMeta();chips.appendChild(chip(vm.chip,vm.tone));if(voiceLine){voiceLine.textContent=vm.detail;voiceLine.dataset.tone=vm.tone;}if(hud){hud.dataset.tone=vm.tone;hud.dataset.mode=S.voice.mode||'idle';}if(hudState)hudState.textContent=vm.chip;if(hudDetail)hudDetail.textContent=vm.detail;if(voiceBtn)voiceBtn.textContent=S.settings.voiceEnabled?'Sesi Durdur':'Sesi Başlat';if(cbBridge)cbBridge.checked=!!S.settings.bridgeEnabled;if(cbAuto)cbAuto.checked=!!S.settings.autoRun;if(S.voice.mode!=='command')setMeters('0%');void postOverlay(false);};
function inHadesRoot(node){if(!root||!node)return false;if(node===root)return true;if(node.nodeType===Node.TEXT_NODE)return inHadesRoot(node.parentNode);return !!(root.contains(node)||node.closest?.('#hades-bridge-root'));}
function relevantDomNode(node){if(!node)return false;if(node.nodeType===Node.TEXT_NODE)return relevantDomNode(node.parentNode);if(!(node instanceof Element)||inHadesRoot(node))return false;if(node.matches('#thread,#thread-bottom-container,#page-header,#prompt-textarea,form.group\\/composer,[data-message-author-role],article,pre,code'))return true;return !!node.querySelector('#thread,#thread-bottom-container,#page-header,#prompt-textarea,form.group\\/composer,[data-message-author-role],article,pre,code');}
function relevantDomMutation(mutations=[]){for(const mutation of mutations){if(inHadesRoot(mutation.target))continue;const nodes=[mutation.target,...mutation.addedNodes,...mutation.removedNodes];for(const node of nodes)if(relevantDomNode(node))return true;}return false;}
function alertSig(alert=null){if(!alert||typeof alert!=='object'||alert.active===false)return'';return JSON.stringify([alert.id||'',alert.kind||'',alert.time||'',alert.message||'',alert.spokenText||'',alert.triggeredAtISO||'']);}
function clearAlertLoop(){if(S.alert.repeatTimer){clearTimeout(S.alert.repeatTimer);S.alert.repeatTimer=0;}S.alert.loopEpoch+=1;}
async function dismissActiveAlert(reason=''){const active=S.alert.active;if(!active)return;clearAlertLoop();S.alert.active=null;render();try{if(active.id)await bridge({type:'bridge:dismiss-active-alert',id:active.id});S.alert.lastSig='';}catch(_){S.alert.active=active;S.alert.lastSig=alertSig(active);render();startAlertLoop();return;}if(reason)log(reason);}
function cleanupReminderSpeechMessage(text=''){return String(text||'').replace(/^\s*(?:hatirlatma|hatırlatma|hatirlatmam|hatırlatmam|hatirlatici|hatırlatıcı)\s*[:,-]?\s*/iu,'').replace(/\s+/g,' ').trim();}
function activeAlertSpeechText(alert=null){if(!alert||typeof alert!=='object')return'Uyan babacığım, vakit geldi.';if(String(alert.kind||'')==='reminder'){const clean=cleanupReminderSpeechMessage(String(alert.message||''));return clean?`Hatırlatmam: ${clean}`:'Hatırlatmam var.';}return alert.spokenText||alert.detail||'Uyan babacığım, vakit geldi.';}
function startAlertLoop(){const active=S.alert.active;if(!active||!S.settings.voiceEnabled)return;clearAlertLoop();const epoch=S.alert.loopEpoch;const tick=()=>{if(epoch!==S.alert.loopEpoch)return;const current=S.alert.active;if(!current||!S.settings.voiceEnabled)return;if(S.voice.reply)S.voice.reply=null;cancelSpeech();if(!S.voice.recognizer&&!S.voice.cmd)void startWake('speaking_interrupt');speak(activeAlertSpeechText(current),()=>{if(epoch!==S.alert.loopEpoch||!S.alert.active||!S.settings.voiceEnabled)return;S.alert.repeatTimer=setTimeout(tick,ALERT_REPEAT_DELAY);},{interruptible:false});};tick();}
async function applyActiveAlert(alert){const next=alert&&typeof alert==='object'&&alert.active!==false?alert:null,nextSig=alertSig(next),sameSig=nextSig===S.alert.lastSig;if(sameSig&&Boolean(S.alert.active)===Boolean(next)){S.alert.active=next;render();return;}clearAlertLoop();S.alert.active=next;S.alert.lastSig=nextSig;render();if(!next)return;if(S.voice.cmd)await stopCmd(true);S.voice.reply=null;log(next.kind==='reminder'?'Hatırlatıcı zamanı geldi.':'Alarm zamanı geldi.');startAlertLoop();}
async function syncActiveAlert(force=false){if(S.alert.syncing)return;const now=Date.now();if(!force&&now-S.alert.lastPollAt<ALERT_SYNC_INTERVAL)return;S.alert.lastPollAt=now;S.alert.syncing=true;try{const res=await bridge({type:'bridge:get-active-alert'});await applyActiveAlert(res?.ok?res.alert:null);}catch(_){ }finally{S.alert.syncing=false;}}
const ui=()=>{if(root){if(!root.isConnected&&document.documentElement)document.documentElement.appendChild(root);render();return;}root=document.createElement('div');root.id='hades-bridge-root';const tog=document.createElement('button');tog.id='hades-bridge-toggle';tog.type='button';tog.textContent='HDS';tog.onclick=()=>panel.dataset.open=String(panel.dataset.open!=='true');hud=document.createElement('aside');hud.id='hades-voice-hud';hud.innerHTML='<p class="hades-voice-hud-kicker">HADES Ses</p><strong class="hades-voice-hud-state" data-role="hud-state"></strong><p class="hades-voice-hud-detail" data-role="hud-detail"></p><div class="hades-voice-hud-meter"><span data-role="hud-meter"></span></div>';panel=document.createElement('section');panel.id='hades-bridge-panel';panel.dataset.open='true';panel.innerHTML=`<div class="hades-bridge-header"><div class="hades-bridge-brand"><img class="hades-bridge-logo" src="${LOGO_URL}" alt="HADES logo"/><div class="hades-bridge-brand-copy"><p class="hades-bridge-kicker">HADES Oturumu</p><h2 class="hades-bridge-title">HADES</h2></div></div><p class="hades-bridge-subtitle">Normal ChatGPT sohbeti, AI tool çağrıları, Google speech wake word, Deepgram komut ve Chromium sesi tek akışta.</p></div><div class="hades-bridge-body"><div class="hades-bridge-chip-row" data-role="chips"></div><div class="hades-bridge-actions"><button type="button" data-a="context">Promptu Gönder</button><button type="button" data-a="voice" data-style="secondary">Sesi Başlat</button><button type="button" data-a="refresh" data-style="secondary">Durumu Yenile</button><button type="button" data-a="spotify" data-style="secondary">Spotify Bağla</button></div><div class="hades-bridge-voice-card"><div class="hades-bridge-voice-status" data-role="voice"></div><div class="hades-bridge-voice-meter"><span data-role="meter"></span></div></div><div class="hades-bridge-toggle-row"><label><input type="checkbox" data-s="bridgeEnabled"/> Köprü aktif</label><span>Sadece AI ürettiği araçlar çalışır</span></div><div class="hades-bridge-toggle-row"><label><input type="checkbox" data-s="autoRun"/> Otomatik çalıştır</label><span>Tool JSON çıkınca direkt uygula</span></div><div class="hades-bridge-log" data-role="log"></div></div>`;
chips=panel.querySelector('[data-role="chips"]');logEl=panel.querySelector('[data-role="log"]');voiceLine=panel.querySelector('[data-role="voice"]');hudState=hud.querySelector('[data-role="hud-state"]');hudDetail=hud.querySelector('[data-role="hud-detail"]');meter=panel.querySelector('[data-role="meter"]');hudMeter=hud.querySelector('[data-role="hud-meter"]');voiceBtn=panel.querySelector('[data-a="voice"]');cbBridge=panel.querySelector('input[data-s="bridgeEnabled"]');cbAuto=panel.querySelector('input[data-s="autoRun"]');toastHost=document.createElement('div');toastHost.id='hades-bridge-toast-host';panel.querySelector('[data-a="context"]').onclick=()=>void sendContext();panel.querySelector('[data-a="refresh"]').onclick=()=>void refresh(true);panel.querySelector('[data-a="spotify"]').onclick=()=>void spotifyLogin();voiceBtn.onclick=()=>void setSetting('voiceEnabled',!S.settings.voiceEnabled);cbBridge.onchange=()=>void setSetting('bridgeEnabled',cbBridge.checked);cbAuto.onchange=()=>void setSetting('autoRun',cbAuto.checked);root.append(hud,tog,panel,toastHost);document.documentElement.appendChild(root);render();};
const brand=()=>{if(root&&!root.isConnected&&document.documentElement)document.documentElement.appendChild(root);if(document.title!=='HADES')document.title='HADES';document.documentElement.setAttribute('data-hades-shell','true');};
const bridge=async(m)=>{const res=await chrome.runtime.sendMessage(m);if(res?.ok===false&&res?.error){const type=String(m?.type||'type_yok');console.warn('[HADES bridge error]',type,res.error);}return res;};
function emitWakeControl(detail={}){window.postMessage({__hadesWakeBridge:true,direction:'to-page',...detail},'*');}
function clearWakeAck(){if(!S.voice.wakeAck)return;clearTimeout(S.voice.wakeAck);S.voice.wakeAck=0;}
async function waitForWakeBridgeReady(timeoutMs=WAKE_READY_TIMEOUT){const startedAt=Date.now();while(Date.now()-startedAt<timeoutMs){if(document.documentElement.dataset.hadesWakeBridge==='ready')return true;await sleep(50);}return document.documentElement.dataset.hadesWakeBridge==='ready';}
async function ensureWakeBridge(){if(document.documentElement.dataset.hadesWakeBridge==='ready')return true;const res=await bridge({type:'bridge:ensure-wake-main-world'});if(!res?.ok)throw new Error(res?.error||'Wake-word köprüsü yüklenemedi.');if(await waitForWakeBridgeReady())return true;document.documentElement.dataset.hadesWakeBridge='';const retry=await bridge({type:'bridge:ensure-wake-main-world'});if(!retry?.ok)throw new Error(retry?.error||'Wake-word köprüsü ikinci denemede yüklenemedi.');if(await waitForWakeBridgeReady())return true;throw new Error('Wake-word köprüsü hazır sinyali vermedi.');}
function bindWakeBridge(){if(wakeBridgeBound)return;wakeBridgeBound=true;window.addEventListener('message',(event)=>{if(event.source!==window)return;const detail=event.data||{};if(!detail.__hadesWakeBridge||detail.direction!=='to-content')return;const type=String(detail.type||''),epoch=Number(detail.epoch)||0,current=S.voice.recognizer,matches=current&&current.kind==='page-bridge'&&current.epoch===epoch;if(type==='ready'){document.documentElement.dataset.hadesWakeBridge='ready';return;}if(type==='unsupported'){clearWakeAck();S.voice.err='Tarayıcı wake-word motoru desteklenmiyor.';render();log(S.voice.err);return;}if(!matches)return;if(type==='started'){clearWakeAck();const shouldLogStart=S.voice.mode!=='wake';if(!S.voice.speaking)S.voice.mode='wake';S.voice.err='';render();if(shouldLogStart)log('Wake-word motoru dinlemeye başladı.');return;}if(type==='wake'){clearWakeAck();void onWake(String(detail.transcript||S.voice.wakeWord));return;}if(type==='error'){clearWakeAck();const err=String(detail.error||'unknown');if(err==='aborted'&&S.voice.wakeStopping)return;if(WAKE_TRANSIENT_ERRORS.has(err)){S.voice.err='';if(!S.voice.speaking)S.voice.mode='wake';render();void stopWake(true,'wake').then(()=>scheduleWake(WAKE_TRANSIENT_ERRORS.get(err)||WAKE_RESTART));return;}S.voice.err=err==='not-allowed'||err==='service-not-allowed'?'Mikrofon izni gerekli.':`Wake-word hatası: ${err}`;render();log(S.voice.err);if(err!=='not-allowed'&&err!=='service-not-allowed'){void stopWake(true,'wake').then(()=>scheduleWake());}return;}if(type==='ended'){clearWakeAck();S.voice.recognizer=null;S.voice.wake=null;if(S.voice.wakeStopping)return;if(!S.voice.cmd&&!S.voice.reply&&S.settings.voiceEnabled){if(!S.voice.speaking)S.voice.mode='wake';render();scheduleWake();}}});}
const ownerVisible=()=>document.visibilityState==='visible'&&document.hasFocus();
function stopOwnerHeartbeat(){if(S.voice.ownerBeat){clearInterval(S.voice.ownerBeat);S.voice.ownerBeat=0;}}
function scheduleOwnerClaim(ms=VOICE_OWNER_RETRY){if(S.voice.ownerRetry)clearTimeout(S.voice.ownerRetry);S.voice.ownerRetry=setTimeout(()=>{S.voice.ownerRetry=0;void claimVoiceOwner('retry');},ms);}
async function releaseVoiceOwner(){stopOwnerHeartbeat();if(S.voice.ownerRetry){clearTimeout(S.voice.ownerRetry);S.voice.ownerRetry=0;}try{await bridge({type:'bridge:release-voice-owner',instanceId:S.voice.instanceId,visible:ownerVisible()});}catch(_){}S.voice.owner=false;}
async function relinquishVoice(){stopSchedule();clearCmd();S.voice.reply=null;S.voice.err='';cancelSpeech();await stopWake(true);await stopCmd(true);await dispose(true);S.voice.mode=S.settings.voiceEnabled?'idle':'off';render();}
function startOwnerHeartbeat(){if(S.voice.ownerBeat)return;S.voice.ownerBeat=setInterval(async()=>{let r=null;try{r=await bridge({type:'bridge:heartbeat-voice-owner',instanceId:S.voice.instanceId,visible:ownerVisible()});}catch(_){}if(r?.ok&&r.owner)return;stopOwnerHeartbeat();if(S.voice.owner){S.voice.owner=false;await relinquishVoice();}scheduleOwnerClaim();},VOICE_OWNER_HEARTBEAT);}
async function claimVoiceOwner(reason='manual'){if(!S.settings.voiceEnabled)return false;if(S.voice.owner){startOwnerHeartbeat();return true;}if(S.voice.ownerRetry){clearTimeout(S.voice.ownerRetry);S.voice.ownerRetry=0;}let r=null;try{r=await bridge({type:'bridge:claim-voice-owner',instanceId:S.voice.instanceId,visible:ownerVisible()});}catch(_){}if(r?.ok&&r.owner){const became=!S.voice.owner;S.voice.owner=true;S.voice.err='';startOwnerHeartbeat();if(became&&(reason==='manual'||reason==='bootstrap'||reason==='focus'))log('Ses yetkisi bu pencereye alindi.');render();return true;}if(S.voice.owner){S.voice.owner=false;await relinquishVoice();}scheduleOwnerClaim();render();return false;}
async function setSetting(key,val){const r=await bridge({type:'bridge:set-settings',patch:{[key]:val}});if(!r?.ok){log(r?.error||'Ayar kaydedilemedi.');return;}S.settings=r.settings;render();if(key==='voiceEnabled'){if(val){toast('Ses akışı açıldı.','ok');await syncActiveAlert(true);if(!S.alert.active)await startWake('setting');}else{toast('Ses akışı kapatıldı.','warn');clearAlertLoop();await releaseVoiceOwner();await stopVoice('setting');}}}
async function refresh(manual=false){const r=await bridge({type:'bridge:get-runtime-status'});if(!r?.ok){S.backendOk=false;S.backendError=r?.error||'Durum alınamadı.';render();if(manual)log(S.backendError);return;}S.backendOk=!!r.backendOk;S.spotify=r.spotify;S.backendError=r.backendError||null;render();if(manual)log(S.backendOk?'Backend durumu yenilendi.':(S.backendError||'Backend kapalı.'));}
async function loadSettings(){const r=await bridge({type:'bridge:get-settings'});if(r?.ok&&r.settings)S.settings=r.settings;render();}
async function loadContext(){const r=await bridge({type:'bridge:get-context-prompt'});if(!r?.ok)throw new Error(r?.error||'Bridge context alınamadı.');S.prompt=String(r.prompt||'');S.promptVersion=String(r.context?.version||'');return S.prompt;}
async function loadVoiceCfg(){let r=await bridge({type:'bridge:get-voice-config'});if(!r?.ok){for(const base of BACKENDS){try{const res=await fetch(`${base}/bridge/voice-config`);if(!res.ok)continue;r=await res.json();break;}catch(_){}}}if(!r||r.ok===false)r={deepgramConfigured:false,deepgramApiKey:'',wakeWord:'HADES',locale:'tr-TR',degraded:true};S.voice.cfg=true;S.voice.err='';S.voice.key=String(r.deepgramApiKey||'').trim();S.voice.wakeWord=String(r.wakeWord||'HADES').trim()||'HADES';S.voice.locale=String(r.locale||'tr-TR').trim()||'tr-TR';render();return r;}
function wakeRecognitionCtor(){return window.SpeechRecognition||window.webkitSpeechRecognition||null;}
async function spotifyLogin(){const r=await bridge({type:'bridge:open-spotify-login'});log(r?.ok?(r.message||'Spotify bağlantı penceresi açıldı.'):(r?.error||'Spotify bağlanamadı.'));await refresh(false);}
async function sendContext(){try{await sendChat(await loadContext());log('HADES proje promptu sohbete gönderildi.');}catch(e){log(e.message||'Prompt gönderilemedi.');}}
const composer=()=>document.querySelector('#prompt-textarea')||document.querySelector('div[contenteditable="true"][id="prompt-textarea"]')||document.querySelector('textarea[data-testid="textbox"]')||document.querySelector('textarea');
async function waitComposer(t=20000){const s=Date.now();while(Date.now()-s<t){const c=composer();if(c)return c;await sleep(250);}throw new Error('HADES mesaj kutusu bulunamadı.');}
function put(c,text){if(!c)return;c.focus();if(c.tagName==='TEXTAREA'){c.value=text;c.dispatchEvent(new Event('input',{bubbles:true}));c.dispatchEvent(new Event('change',{bubbles:true}));return;}try{document.execCommand('selectAll',false);document.execCommand('insertText',false,text);}catch(_){}if(String(c.textContent||'').trim()!==String(text||'').trim()){c.innerHTML='';const p=document.createElement('p');p.textContent=text;c.appendChild(p);}c.dispatchEvent(new InputEvent('input',{bubbles:true,data:text,inputType:'insertText'}));c.dispatchEvent(new Event('change',{bubbles:true}));}
function composerText(c=composer()){if(!c)return'';return cleanupSpaces(c.tagName==='TEXTAREA'?String(c.value||''):String(c.textContent||''));}
function clearComposer(c=composer()){if(!c)return;put(c,'');}
const sendBtn=()=>document.querySelector('button[data-testid="send-button"]')||document.querySelector('button[aria-label^="Send"]')||document.querySelector('button[aria-label*="Gonder"]')||document.querySelector('button[aria-label*="Gönder"]');
const stopBtn=()=>document.querySelector('button[data-testid="stop-button"]')||document.querySelector('button[aria-label^="Stop"]')||document.querySelector('button[aria-label*="Durdur"]')||document.querySelector('button[aria-label*="Yanitlamayi durdur"]')||document.querySelector('button[aria-label*="Yanıtlamayı durdur"]');
async function stopAnswer(){const b=stopBtn();if(!b||b.disabled)return false;b.click();await sleep(120);log('Model yanıtı durduruldu.');return true;}
async function clickSend(){const s=Date.now();while(Date.now()-s<5000){const b=sendBtn();if(b&&!b.disabled){b.click();return true;}await sleep(150);}const c=composer();if(c){c.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));return true;}return false;}
async function sendChat(text){S.programmatic=true;try{const c=await waitComposer();put(c,text);await sleep(180);if(!(await clickSend()))throw new Error('Mesaj gönderilemedi.');}finally{setTimeout(()=>{S.programmatic=false;},250);}}
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const toast=(m,t='info')=>{if(!toastHost)return;const e=document.createElement('div');e.className='hades-bridge-toast';e.dataset.tone=t;e.textContent=m;toastHost.appendChild(e);setTimeout(()=>{e.classList.add('is-leaving');setTimeout(()=>e.remove(),320);},3200);};
function cleanupSpaces(text=''){return String(text||'').replace(/\s+/g,' ').trim();}
function extractDirectScheduleIntent(text=''){if(globalThis.HADESScheduleIntent?.extractLocalScheduleIntent)return globalThis.HADESScheduleIntent.extractLocalScheduleIntent(text);return null;}
async function runDirectLocalIntent(rawText,source='voice'){const cleaned=cleanupSpaces(rawText);const intent=extractDirectScheduleIntent(cleaned);if(!intent)return false;S.exec=true;try{await stopAnswer();log(`Yerel zamanlayıcı komutu doğrudan işlendi: ${intent.tool}`);const r=await bridge({type:'bridge:execute-actions',actions:[intent]});const results=Array.isArray(r?.results)&&r.results.length?r.results.map(x=>({tool:x.tool,ok:x.ok,status:x.status||null,data:x.data||null,error:x.error||null})):[{tool:intent.tool,ok:false,status:null,data:null,error:r?.error||'Yerel araç sonucu alınamadı.'}];S.voice.reply={count:speakableAssistant().length,started:Date.now(),sig:'',stable:0};S.voice.mode='reply';render();await sendChat(['HADES_TOOL_RESULT',JSON.stringify({ok:results.every(x=>x.ok),source,directLocalIntent:true,userCommand:cleaned,results},null,2)].join('\n'));log('Yerel zamanlayıcı sonucu sohbete geri yazıldı.');await refresh(false);return true;}catch(e){S.voice.reply=null;S.voice.err=e.message||'Yerel zamanlayıcı komutu gönderilemedi.';render();log(S.voice.err);if(source==='voice'&&S.settings.voiceEnabled)await startWake('send_failed');return true;}finally{S.exec=false;}}
function bindManualScheduleInterceptors(){if(manualScheduleBound)return;manualScheduleBound=true;document.addEventListener('keydown',(event)=>{if(S.programmatic||event.defaultPrevented||event.isComposing||event.key!=='Enter'||event.shiftKey)return;const c=composer();if(!c)return;const target=event.target;if(target!==c&&!(target&&typeof c.contains==='function'&&c.contains(target)))return;const raw=composerText(c);if(!extractDirectScheduleIntent(raw))return;event.preventDefault();event.stopImmediatePropagation();clearComposer(c);void runDirectLocalIntent(raw,'typed');},true);document.addEventListener('click',(event)=>{if(S.programmatic||event.defaultPrevented)return;const target=event.target;if(!target||typeof target.closest!=='function')return;const btn=target.closest('button[data-testid="send-button"],button[aria-label^="Send"],button[aria-label*="Gonder"],button[aria-label*="Gönder"]');if(!btn)return;const c=composer();const raw=composerText(c);if(!extractDirectScheduleIntent(raw))return;event.preventDefault();event.stopImmediatePropagation();clearComposer(c);void runDirectLocalIntent(raw,'typed');},true);}
function initVoices(){if(!('speechSynthesis' in window))return;const vs=window.speechSynthesis.getVoices();S.voice.prefVoice=vs.find(v=>v.name==='Google Türkçe'&&v.lang==='tr-TR')||vs.find(v=>v.lang==='tr-TR')||null;window.speechSynthesis.onvoiceschanged=initVoices;}
function stripSpeechPayloads(text=''){let out=String(text||'');out=out.replace(/```(?:hades-bridge|json)?[\s\S]*?```/gi,' ');while(out.includes('"actions"')){const i=out.indexOf('"actions"'),o=out.lastIndexOf('{',i);if(o<0)break;const chunk=balanced(out,o);if(!chunk)break;out=`${out.slice(0,o)} ${out.slice(o+chunk.length)}`;}return out;}
function stripEmoji(text=''){return String(text||'').replace(/[\p{Extended_Pictographic}\p{Emoji_Presentation}\uFE0F]/gu,' ');}
function collapseRepeat(text=''){const clean=String(text||'').replace(/\s+/g,' ').trim();if(!clean)return'';const words=clean.split(' ');if(words.length>=4&&words.length%2===0){const half=words.length/2,left=words.slice(0,half).join(' '),right=words.slice(half).join(' ');if(norm(left)===norm(right))return left;}return clean;}
function speechText(text=''){return collapseRepeat(stripEmoji(stripSpeechPayloads(String(text||'')).replace(/HADES_TOOL_RESULT[\s\S]*$/gi,' ').replace(/HADES_RUNTIME_STATUS[\s\S]*$/gi,' ').replace(/HADES_LOCAL_EXECUTION[\s\S]*$/gi,' ').replace(/HADES_BRIDGE_PROFILE_V\d+/gi,' '))).replace(/\s+/g,' ').trim();}
function cancelSpeech(reason=''){S.voice.ttsEpoch+=1;if('speechSynthesis' in window)try{window.speechSynthesis.cancel();}catch(_){}if(S.voice.speaking){S.voice.speaking=false;S.voice.mode=S.voice.recognizer?'wake':(S.settings.voiceEnabled?'idle':'off');render();}if(reason)log(reason);}
function speak(text,onEnd=null,opts={}){const m=speechText(text),id=S.voice.ttsEpoch+1,interruptible=opts.interruptible!==false;if(!m||!('speechSynthesis' in window)){if(onEnd)onEnd();return;}try{S.voice.ttsEpoch=id;window.speechSynthesis.cancel();S.voice.speaking=true;S.voice.mode='speaking';render();const u=new SpeechSynthesisUtterance(m);u.lang=S.voice.locale||'tr-TR';u.rate=1.02;u.pitch=1;if(S.voice.prefVoice)u.voice=S.voice.prefVoice;u.onend=()=>{if(id!==S.voice.ttsEpoch)return;S.voice.speaking=false;if(!S.voice.reply)S.voice.mode=S.voice.recognizer?'wake':(S.settings.voiceEnabled?'idle':'off');render();if(onEnd)onEnd();};u.onerror=()=>{if(id!==S.voice.ttsEpoch)return;S.voice.speaking=false;S.voice.err='Tarayıcı sesi oynatılamadı.';render();if(onEnd)onEnd();};window.speechSynthesis.speak(u);if(interruptible&&S.settings.voiceEnabled)setTimeout(()=>{if(id===S.voice.ttsEpoch&&S.voice.speaking&&!S.voice.recognizer&&!S.voice.cmd)void startWake('speaking_interrupt');},320);}catch(_){S.voice.speaking=false;render();if(onEnd)onEnd();}}
function sig(text){let h=0;const n=String(text||'');for(let i=0;i<n.length;i+=1){h=((h<<5)-h)+n.charCodeAt(i);h|=0;}return `${n.length}:${h}`;}
function parsePayload(text){const t=String(text||'').trim();if(!t.startsWith('{')||!t.includes('"actions"'))return null;try{const p=JSON.parse(t);return Array.isArray(p.actions)&&p.actions.length?p:null;}catch(_){return null;}}
function balanced(text,start){let d=0,s=false,e=false;for(let i=start;i<text.length;i+=1){const c=text[i];if(s){if(e){e=false;continue;}if(c==='\\'){e=true;continue;}if(c==='"')s=false;continue;}if(c==='"'){s=true;continue;}if(c==='{'){d+=1;continue;}if(c==='}'){d-=1;if(d===0)return text.slice(start,i+1);}}return '';}
function payloadFrom(text){const raw=String(text||'').trim();if(!raw.includes('"actions"'))return null;for(const m of raw.matchAll(/```(?:hades-bridge|json)\s*([\s\S]*?)```/gi)){const p=parsePayload(m[1]||'');if(p)return p;}if(raw.startsWith('{')&&raw.endsWith('}'))return parsePayload(raw);const i=raw.indexOf('"actions"');if(i>=0){const o=raw.lastIndexOf('{',i);if(o>=0){const p=parsePayload(balanced(raw,o));if(p)return p;}}return null;}
function hideTech(text){const t=String(text||'').trim();if(!t)return false;if(t.startsWith('HADES_BRIDGE_PROFILE_V'))return true;if(t.includes('Çalışma protokolü:')&&t.includes('Kullanabileceğin yerel araçlar:'))return true;if(t.startsWith('HADES_TOOL_RESULT')||t.startsWith('HADES_RUNTIME_STATUS')||t.startsWith('HADES_LOCAL_EXECUTION'))return true;const p=payloadFrom(t);if(!p)return false;return t.replace(/```(?:hades-bridge|json)?/gi,'').replace(/```/g,'').trim().length<2000;}
function assistantNodes(){return [...document.querySelectorAll('[data-message-author-role="assistant"],article[data-message-author-role="assistant"]')];}
function messageNodes(){return [...document.querySelectorAll('[data-message-author-role],article')];}
function seed(){messageNodes().forEach(n=>{S.processed.add(n);n.querySelectorAll('pre code').forEach(c=>S.processed.add(c));});}
function decorate(){messageNodes().forEach(n=>{const t=String(n.textContent||'').trim();if(hideTech(t))n.classList.add('hades-bridge-hidden-message');});}
function speakableAssistant(){return assistantNodes().filter(n=>{const t=String(n.textContent||'').trim();return t&&!hideTech(t);});}
async function scanBridge(){if(!S.settings.bridgeEnabled||S.exec)return;const candidates=[...assistantNodes().flatMap(n=>Array.from(n.querySelectorAll('pre code'))),...assistantNodes()];for(const c of candidates){if(S.processed.has(c))continue;const text=String(c.textContent||'');if(text.startsWith('HADES_BRIDGE_PROFILE_V')||(text.includes('Çalışma protokolü:')&&text.includes('Kullanabileceğin yerel araçlar:'))){S.processed.add(c);continue;}const payload=payloadFrom(text);if(!payload)continue;const s=sig(JSON.stringify(payload));const last=S.seen.get(s);const now=Date.now();S.seen.set(s,now);for(const [k,v] of S.seen.entries())if(now-v>20000)S.seen.delete(k);S.processed.add(c);if(last&&now-last<15000)continue;if(!S.settings.autoRun){const ok=window.confirm(`HADES Bridge bu araçları çalıştırsın mı?\n${payload.actions.map(a=>a.tool).join(', ')}`);if(!ok){log('Araç çağrısı kullanıcı tarafından iptal edildi.');continue;}}await execBridge(payload);break;}}
async function execBridge(payload){S.exec=true;try{await stopAnswer();log(`Araç çağrısı yakalandı: ${payload.actions.map(a=>a.tool).join(', ')}`);const r=await bridge({type:'bridge:execute-actions',actions:payload.actions});if(!r?.results)throw new Error(r?.error||'Araç sonucu alınamadı.');const results=r.results.map(x=>({tool:x.tool,ok:x.ok,status:x.status||null,data:x.data||null,error:x.error||null}));await sendChat(['HADES_TOOL_RESULT',JSON.stringify({ok:!!r.ok,results},null,2)].join('\n'));log('Yerel araç sonucu sohbete geri yazıldı.');await refresh(false);}catch(e){log(e.message||'Araç çağrısı işlenemedi.');}finally{S.exec=false;}}
function norm(text=''){if(globalThis.HADESWakeWord?.norm)return globalThis.HADESWakeWord.norm(text);return String(text||'').toLocaleLowerCase('tr-TR').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/\u0131/g,'i').replace(/[^\w\s]/g,' ').replace(/\s+/g,' ').trim();}
function wakeTokenMatch(token=''){if(globalThis.HADESWakeWord?.wakeTokenMatch)return globalThis.HADESWakeWord.wakeTokenMatch(token);const t=norm(token);if(!t)return false;if(['hades','hedes','ades','hadesi','hadesin','hadesim','hds','hadese','hadesya'].includes(t))return true;if(t.startsWith('hades')||t.startsWith('ades')||t.startsWith('hede'))return true;const chars=t.replace(/\s+/g,'');if(chars.length<3||chars.length>7)return false;let score=0;if(chars.includes('h'))score+=1;if(chars.includes('a'))score+=1;if(chars.includes('d'))score+=1;if(chars.includes('e'))score+=1;if(chars.includes('s'))score+=1;return score>=4;}
function hasWake(text=''){if(globalThis.HADESWakeWord?.hasWake)return globalThis.HADESWakeWord.hasWake(text);const cleaned=norm(text);if(!cleaned)return false;if(/\b(hades|ha des|hedes|ades)\b/.test(cleaned))return true;return cleaned.split(' ').some(wakeTokenMatch);}
function isWakeOnly(text=''){if(globalThis.HADESWakeWord?.isWakeOnly)return globalThis.HADESWakeWord.isWakeOnly(text);const cleaned=norm(text);if(!cleaned||!hasWake(cleaned))return false;const rest=cleaned.split(' ').filter((part)=>!wakeTokenMatch(part)).join(' ').trim();return !rest;}
function stripWake(text=''){if(globalThis.HADESWakeWord?.stripWake)return globalThis.HADESWakeWord.stripWake(text);const raw=String(text||'').trim();if(!raw)return'';const p=raw.replace(WAKE_PREFIX,'').trim();if(p!==raw)return p;const m=raw.match(WAKE);if(!m||m.index===undefined)return raw;return raw.slice(m.index+m[0].length).replace(/^[\s,.:;!?-]+/,'').trim();}
function extractWakeCommand(text=''){if(globalThis.HADESWakeWord?.extractWakeCommand)return globalThis.HADESWakeWord.extractWakeCommand(text);return stripWake(text);}
async function watchReplies(){const p=S.voice.reply;if(!p||S.exec||stopBtn()||S.alert.active)return;const nodes=speakableAssistant();if(nodes.length<=p.count){if(Date.now()-p.started>REPLY_TIMEOUT){log('Sesli yanıt bekleme zaman aşımına uğradı.');S.voice.reply=null;if(S.settings.voiceEnabled)await startWake('reply_timeout');}return;}const txt=speechText(String(nodes[nodes.length-1]?.textContent||''));if(!txt){S.voice.reply=null;if(S.settings.voiceEnabled)await startWake('empty_reply');return;}const s=sig(txt);if(s!==p.sig){p.sig=s;p.stable=Date.now();return;}if(Date.now()-p.stable<900)return;S.voice.reply=null;if(S.voice.lastSig===s){if(S.settings.voiceEnabled)await startWake('duplicate_reply');return;}S.voice.lastSig=s;log('HADES yanıtı seslendiriliyor.');speak(txt,()=>{if(S.settings.voiceEnabled)void startCmd('followup',{mode:'followup',timeoutMs:FOLLOWUP_TIMEOUT,silentNoSpeech:true});});}
function runDomMaintenance(){domQueued=false;if(domTimer){clearTimeout(domTimer);domTimer=0;}ui();brand();decorate();void scanBridge();void watchReplies();void syncActiveAlert();}
function runIdleMaintenance(){if(root&&!root.isConnected&&document.documentElement)document.documentElement.appendChild(root);brand();if(S.voice.reply)void watchReplies();void syncActiveAlert();}
function queueDomMaintenance(delay=DOM_MUTATION_DEBOUNCE){if(domQueued)return;domQueued=true;domTimer=setTimeout(runDomMaintenance,delay);}
function observe(){if(obs)return;seed();decorate();obs=new MutationObserver((mutations)=>{if(relevantDomMutation(mutations))queueDomMaintenance();});obs.observe(document.documentElement,{childList:true,subtree:true});}
async function mic(){if(S.voice.stream&&S.voice.stream.active)return S.voice.stream;S.voice.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});return S.voice.stream;}
async function worklet(){if(!S.voice.ctx)return false;const code=`class R extends AudioWorkletProcessor{constructor({processorOptions:{targetSampleRate,inputSampleRate}}){super();this.t=targetSampleRate;this.i=inputSampleRate;}process(inputs){const d=inputs[0][0];if(d)this.port.postMessage(this.down(d));return true;}down(b){const r=this.i/this.t,l=Math.max(1,Math.round(b.length/r)),o=new Int16Array(l);let or=0,ob=0;while(or<l){const n=Math.round((or+1)*r);let a=0,c=0;for(let i=ob;i<n&&i<b.length;i+=1){a+=b[i];c+=1;}o[or]=Math.max(-1,Math.min(1,c>0?(a/c):0))*0x7FFF;or+=1;ob=n;}return o.buffer;}}registerProcessor('resampler-processor',R);`;const blob=new Blob([code],{type:'application/javascript'});const url=URL.createObjectURL(blob);try{await S.voice.ctx.audioWorklet.addModule(url);return true;}finally{URL.revokeObjectURL(url);}}
async function dispose(stopStream=false){if(S.voice.frame){cancelAnimationFrame(S.voice.frame);S.voice.frame=0;}if(S.voice.worklet){try{S.voice.worklet.port.postMessage('stop');S.voice.worklet.disconnect();}catch(_){}S.voice.worklet=null;}if(S.voice.an){try{S.voice.an.disconnect();}catch(_){}S.voice.an=null;}if(S.voice.src){try{S.voice.src.disconnect();}catch(_){}S.voice.src=null;}const ctx=S.voice.ctx;S.voice.ctx=null;if(ctx&&ctx.state!=='closed'){try{await ctx.close();}catch(_){}}if(stopStream&&S.voice.stream){for(const t of S.voice.stream.getTracks())try{t.stop();}catch(_){}S.voice.stream=null;}setMeters('0%');}
function audio(stream,socket,isOpen,showMeter=false){if(!S.voice.ctx)return;S.voice.src=S.voice.ctx.createMediaStreamSource(stream);S.voice.an=S.voice.ctx.createAnalyser();S.voice.an.fftSize=256;const len=S.voice.an.frequencyBinCount,data=new Uint8Array(len);S.voice.worklet=new AudioWorkletNode(S.voice.ctx,'resampler-processor',{processorOptions:{targetSampleRate:16000,inputSampleRate:S.voice.ctx.sampleRate}});S.voice.worklet.port.onmessage=(e)=>{if(!isOpen())return;const d=e.data;if(d.byteLength>0&&socket&&socket.readyState===WebSocket.OPEN)socket.send(d);};S.voice.src.connect(S.voice.an);S.voice.src.connect(S.voice.worklet);if(!showMeter){setMeters('0%');return;}const draw=()=>{if(!isOpen()||!S.voice.an){setMeters('0%');return;}S.voice.frame=requestAnimationFrame(draw);S.voice.an.getByteFrequencyData(data);let sum=0;for(let i=0;i<len;i+=1)sum+=data[i];setMeters(`${Math.min(100,(sum/len/128)*100)}%`);};draw();}
async function prep(){await dispose(false);const stream=await mic();S.voice.ctx=new AudioContext();await worklet();return stream;}
function clearCmd(){if(S.voice.timeout){clearTimeout(S.voice.timeout);S.voice.timeout=0;}}
function scheduleWake(ms=WAKE_RESTART){if(!S.settings.voiceEnabled||S.voice.reply||S.voice.cmd)return;if(S.voice.restart)clearTimeout(S.voice.restart);S.voice.restart=setTimeout(()=>{S.voice.restart=0;void startWake('restart');},ms);}
function stopSchedule(){if(!S.voice.restart)return;clearTimeout(S.voice.restart);S.voice.restart=0;}
async function voiceReady(){if(!S.voice.cfg)await loadVoiceCfg();if(!S.voice.key){S.voice.err='DEEPGRAM_API_KEY eksik.';render();return false;}return true;}
async function stopWake(preserve=true,nextMode='idle'){stopSchedule();clearWakeAck();S.voice.wEpoch+=1;S.voice.wakeStopping=true;const rec=S.voice.recognizer;S.voice.recognizer=null;S.voice.wake=null;if(rec){try{if('onstart'in rec)rec.onstart=null;if('onresult'in rec)rec.onresult=null;if('onerror'in rec)rec.onerror=null;if('onend'in rec)rec.onend=null;if(typeof rec.stop==='function')rec.stop();else if(typeof rec.close==='function')rec.close();else if(rec.socket&&typeof rec.socket.close==='function')rec.socket.close();}catch(_){}}if(!preserve)await dispose(true);S.voice.wakeStopping=false;if(!S.voice.cmd&&!S.voice.reply&&!S.voice.speaking&&S.settings.voiceEnabled){S.voice.mode=nextMode;render();}}
async function stopCmd(preserve=true){S.voice.cEpoch+=1;clearCmd();S.voice.segments=[];S.voice.interim='';S.voice.cmdOptions=null;const s=S.voice.cmd;S.voice.cmd=null;if(s&&(s.readyState===WebSocket.OPEN||s.readyState===WebSocket.CONNECTING))try{s.close();}catch(_){}await dispose(!preserve);if(!S.voice.wake&&!S.voice.reply&&!S.voice.speaking&&S.settings.voiceEnabled){S.voice.mode='idle';render();}}
async function stopVoice(reason='manual'){stopSchedule();clearWakeAck();clearCmd();clearAlertLoop();S.voice.reply=null;S.voice.err='';S.voice.mode='off';cancelSpeech();await stopWake(false);await stopCmd(false);await dispose(true);if(reason!=='setting')log('Ses akışı durduruldu.');render();}
async function startWake(reason='manual'){if(!S.settings.voiceEnabled||!S.settings.bridgeEnabled||S.voice.recognizer||S.voice.cmd||S.voice.reply)return;stopSchedule();clearWakeAck();S.voice.err='';if(!S.voice.cfg)await loadVoiceCfg();bindWakeBridge();try{await ensureWakeBridge();const overlay=S.voice.speaking||reason==='speaking_interrupt',softRestart=reason==='restart'||reason==='focus'||reason==='reply_timeout'||reason==='empty_reply'||reason==='duplicate_reply'||reason==='empty_transcript'||reason==='duplicate_transcript'||reason==='command_error'||reason==='followup_idle'||reason==='no_speech',epoch=++S.voice.wEpoch,session={kind:'page-bridge',epoch,stop(){emitWakeControl({action:'stop',epoch});}};if(!overlay&&!softRestart&&S.voice.mode!=='wake')S.voice.mode='starting';S.voice.recognizer=session;S.voice.wake=session;render();emitWakeControl({action:'start',epoch,lang:S.voice.locale||'tr-TR',wakeWord:S.voice.wakeWord||'HADES'});S.voice.wakeAck=setTimeout(()=>{if(!S.settings.voiceEnabled||S.voice.cmd||S.voice.reply)return;const current=S.voice.recognizer;if(!current||current.kind!=='page-bridge'||current.epoch!==epoch)return;if(S.voice.mode!=='starting')return;document.documentElement.dataset.hadesWakeBridge='';log('Wake-word motoru cevap vermedi, yeniden deneniyor.');void stopWake(true,'idle').then(()=>{if(S.settings.voiceEnabled)scheduleWake(180);});},WAKE_START_ACK_TIMEOUT);if(reason==='manual'||reason==='bootstrap'||reason==='focus'||reason==='setting')log(`Wake-word dinleme aktif: "${S.voice.wakeWord}"`);}catch(e){S.voice.err=e.message||'Wake-word başlatılamadı.';render();log(S.voice.err);if(S.settings.voiceEnabled)scheduleWake();}}
async function onWake(t){log(`Wake-word algılandı: ${t}`);if(S.alert.active){await dismissActiveAlert('Aktif alarm susturuldu.');if(S.voice.speaking){S.voice.reply=null;cancelSpeech();}await stopWake(true);toast('Alarm susturuldu.','ok');if(S.settings.voiceEnabled)await startWake('alert_dismissed');return;}if(S.voice.speaking){S.voice.reply=null;cancelSpeech('HADES yeni komuta odaklandı.');}await stopWake(true);toast('Efendim babacığım.','ok');speak('Efendim babacığım.',()=>{if(S.settings.voiceEnabled)void startCmd('wake_word');},{interruptible:false});}
const compose=(f='')=>[...S.voice.segments,S.voice.interim,f].map(x=>String(x||'').trim()).filter(Boolean).join(' ').replace(/\s+/g,' ').trim();
function mergeSegment(text=''){const next=speechText(text);if(!next)return;const prev=S.voice.segments[S.voice.segments.length-1]||'';if(prev&&norm(prev)===norm(next))return;if(prev&&norm(next).startsWith(norm(prev))){S.voice.segments[S.voice.segments.length-1]=next;return;}S.voice.segments.push(next);}
function normalizeCmdOptions(raw={}){const timeoutMs=Math.max(1800,Number(raw.timeoutMs)||COMMAND_TIMEOUT);return{timeoutMs,silentNoSpeech:!!raw.silentNoSpeech,mode:raw.mode==='followup'?'followup':'command'};}
function resetCmd(){clearCmd();const opts=S.voice.cmdOptions||normalizeCmdOptions();S.voice.timeout=setTimeout(()=>{const t=compose();if(t){void finalizeVoice(t,'silence_timeout');return;}if(opts.silentNoSpeech){void stopCmd(true).then(()=>{if(S.settings.voiceEnabled)void startWake('followup_idle');});return;}log('Ses komutu duyulamadı, wake-word moduna dönülüyor.');toast('Komut duyamadım.','warn');void stopCmd(true).then(()=>{if(S.settings.voiceEnabled)void startWake('no_speech');});},opts.timeoutMs);}
async function startCmd(reason='manual',rawOpts={}){if(!S.settings.voiceEnabled||S.voice.cmd||S.voice.reply||S.voice.speaking)return;if(!(await voiceReady()))return;try{const opts=normalizeCmdOptions(rawOpts),stream=await prep(),epoch=++S.voice.cEpoch,socket=new WebSocket(`${DG}?encoding=linear16&sample_rate=16000&language=tr&model=nova-2&endpointing=500&utterance_end_ms=1200&interim_results=true&smart_format=true`,['token',S.voice.key]);S.voice.segments=[];S.voice.interim='';S.voice.finalizing=false;S.voice.cmdOptions=opts;S.voice.mode=opts.mode;S.voice.cmd=socket;render();const open=()=>epoch===S.voice.cEpoch&&S.voice.cmd===socket&&S.settings.voiceEnabled;socket.onopen=()=>{if(!open()){try{socket.close();}catch(_){}return;}log(opts.mode==='followup'?'Takip dinleme aktif.':`Komut dinleme aktif (${reason}).`);audio(stream,socket,open,true);resetCmd();};socket.onmessage=(m)=>{if(!open())return;let d;try{d=JSON.parse(m.data);}catch(_){return;}const t=speechText(String(d.channel?.alternatives?.[0]?.transcript||'').trim());if(t){if(d.is_final){mergeSegment(t);S.voice.interim='';}else S.voice.interim=t;resetCmd();}if(d.speech_final){void finalizeVoice(compose(t),'speech_final');}};socket.onerror=()=>{if(epoch!==S.voice.cEpoch)return;S.voice.err='Komut dinleme bağlantısı koptu.';render();log('Komut dinleme bağlantısı koptu.');void stopCmd(true).then(()=>{if(S.settings.voiceEnabled)void startWake('command_error');});};socket.onclose=()=>{if(epoch!==S.voice.cEpoch)return;S.voice.cmd=null;};}catch(e){S.voice.err=e.message||'Komut dinleme başlatılamadı.';render();log(S.voice.err);if(S.settings.voiceEnabled)scheduleWake();}}
async function finalizeVoice(raw,reason='final'){if(S.voice.finalizing)return;S.voice.finalizing=true;const text=collapseRepeat(stripWake(speechText(String(raw||'').replace(/\s+/g,' ').trim()))),submitSig=sig(norm(text));try{await stopCmd(true);if(!text){log('Boş ses metni geldi, wake-word moduna dönülüyor.');if(S.settings.voiceEnabled)await startWake('empty_transcript');return;}if(S.voice.lastSubmitSig===submitSig&&Date.now()-S.voice.lastSubmitAt<8000){log('Yinelenen ses metni atlandı.');if(S.settings.voiceEnabled)await startWake('duplicate_transcript');return;}S.voice.lastSubmitSig=submitSig;S.voice.lastSubmitAt=Date.now();if(await runDirectLocalIntent(text,'voice')){toast(`Yerel komut işlendi: ${text}`,'ok');return;}S.voice.reply={count:speakableAssistant().length,started:Date.now(),sig:'',stable:0};S.voice.mode='reply';render();await sendChat(text);log(`Ses metni sohbete gönderildi (${reason}): ${text}`);toast(`HADES'e gitti: ${text}`,'ok');}catch(e){S.voice.reply=null;S.voice.err=e.message||'Ses komutu gönderilemedi.';render();log(S.voice.err);if(S.settings.voiceEnabled)await startWake('send_failed');}finally{S.voice.finalizing=false;}}
async function bootVoice(){try{initVoices();await loadVoiceCfg();if(S.settings.voiceEnabled)await startWake('bootstrap');}catch(e){S.voice.err=e.message||'Ses hazırlanamadı.';render();log(S.voice.err);}}
async function boot(){ui();brand();observe();bindManualScheduleInterceptors();timer=setInterval(runIdleMaintenance,DOM_MAINTENANCE_INTERVAL);await loadSettings();await refresh(false);log('HADES hazır.');await bootVoice();await syncActiveAlert(true);}
window.addEventListener('focus',()=>{if(S.settings.voiceEnabled&&!S.voice.recognizer&&!S.voice.cmd&&!S.voice.reply&&!S.voice.speaking)void startWake('focus');});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&S.settings.voiceEnabled&&!S.voice.recognizer&&!S.voice.cmd&&!S.voice.reply&&!S.voice.speaking)void startWake('focus');});
window.addEventListener('beforeunload',()=>{if(timer){clearInterval(timer);timer=0;}if(domTimer){clearTimeout(domTimer);domTimer=0;}if(obs){obs.disconnect();obs=null;}clearAlertLoop();void releaseVoiceOwner();void stopVoice('beforeunload');});
boot().catch(e=>console.error('HADES Bridge bootstrap hatası:',e));
})();
